# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\18-belousov.n.d\Documents\Diplom\Progarms\disignerFiles\serverNeuronsNetworkGui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(496, 563)
        self.TabWidgetApp = QtWidgets.QTabWidget(Form)
        self.TabWidgetApp.setGeometry(QtCore.QRect(50, 30, 402, 341))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TabWidgetApp.setFont(font)
        self.TabWidgetApp.setObjectName("TabWidgetApp")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hostLabel = QtWidgets.QLabel(self.tab)
        self.hostLabel.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.hostLabel.setFont(font)
        self.hostLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.hostLabel.setObjectName("hostLabel")
        self.verticalLayout_2.addWidget(self.hostLabel)
        self.IPLabel = QtWidgets.QLabel(self.tab)
        self.IPLabel.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.IPLabel.setFont(font)
        self.IPLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.IPLabel.setObjectName("IPLabel")
        self.verticalLayout_2.addWidget(self.IPLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.PortLabel = QtWidgets.QLabel(self.tab)
        self.PortLabel.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.PortLabel.setFont(font)
        self.PortLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.PortLabel.setObjectName("PortLabel")
        self.horizontalLayout_2.addWidget(self.PortLabel)
        self.portLineEdit = QtWidgets.QLineEdit(self.tab)
        self.portLineEdit.setMinimumSize(QtCore.QSize(70, 25))
        self.portLineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.portLineEdit.setFont(font)
        self.portLineEdit.setObjectName("portLineEdit")
        self.horizontalLayout_2.addWidget(self.portLineEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.gifLabel = QtWidgets.QLabel(self.tab)
        self.gifLabel.setMinimumSize(QtCore.QSize(100, 100))
        self.gifLabel.setMaximumSize(QtCore.QSize(100, 100))
        self.gifLabel.setText("")
        self.gifLabel.setObjectName("gifLabel")
        self.horizontalLayout_4.addWidget(self.gifLabel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.StartStopPushButton = QtWidgets.QPushButton(self.tab)
        self.StartStopPushButton.setMinimumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.StartStopPushButton.setFont(font)
        self.StartStopPushButton.setObjectName("StartStopPushButton")
        self.horizontalLayout_3.addWidget(self.StartStopPushButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        spacerItem6 = QtWidgets.QSpacerItem(20, 36, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.infoServerLabel = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.infoServerLabel.setFont(font)
        self.infoServerLabel.setObjectName("infoServerLabel")
        self.verticalLayout_4.addWidget(self.infoServerLabel)
        self.textInfoServer = QtWidgets.QTextEdit(self.tab)
        self.textInfoServer.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textInfoServer.setFont(font)
        self.textInfoServer.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textInfoServer.setObjectName("textInfoServer")
        self.verticalLayout_4.addWidget(self.textInfoServer)
        self.TabWidgetApp.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.clientsTableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.clientsTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed)
        self.clientsTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.clientsTableWidget.setObjectName("clientsTableWidget")
        self.clientsTableWidget.setColumnCount(0)
        self.clientsTableWidget.setRowCount(0)
        self.verticalLayout_3.addWidget(self.clientsTableWidget)
        self.TabWidgetApp.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.dirNetworkLabel = QtWidgets.QLabel(self.tab_3)
        self.dirNetworkLabel.setObjectName("dirNetworkLabel")
        self.horizontalLayout_5.addWidget(self.dirNetworkLabel)
        self.dirNetworkLineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.dirNetworkLineEdit.setMinimumSize(QtCore.QSize(0, 25))
        self.dirNetworkLineEdit.setObjectName("dirNetworkLineEdit")
        self.horizontalLayout_5.addWidget(self.dirNetworkLineEdit)
        self.dirButton = QtWidgets.QPushButton(self.tab_3)
        self.dirButton.setMaximumSize(QtCore.QSize(30, 25))
        self.dirButton.setObjectName("dirButton")
        self.horizontalLayout_5.addWidget(self.dirButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.neuronGifLabel = QtWidgets.QLabel(self.tab_3)
        self.neuronGifLabel.setMinimumSize(QtCore.QSize(200, 100))
        self.neuronGifLabel.setMaximumSize(QtCore.QSize(400, 200))
        self.neuronGifLabel.setObjectName("neuronGifLabel")
        self.horizontalLayout_6.addWidget(self.neuronGifLabel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.TabWidgetApp.addTab(self.tab_3, "")

        self.retranslateUi(Form)
        self.TabWidgetApp.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.hostLabel.setText(_translate("Form", "Хост: "))
        self.IPLabel.setText(_translate("Form", "IPv4-адрес: "))
        self.PortLabel.setText(_translate("Form", "Порт: "))
        self.StartStopPushButton.setText(_translate("Form", "старт"))
        self.infoServerLabel.setText(_translate("Form", "Информация об работе сервера:"))
        self.TabWidgetApp.setTabText(self.TabWidgetApp.indexOf(self.tab), _translate("Form", "Сервер"))
        self.TabWidgetApp.setTabText(self.TabWidgetApp.indexOf(self.tab_2), _translate("Form", "Клиенты"))
        self.dirNetworkLabel.setText(_translate("Form", "Путь:"))
        self.dirButton.setText(_translate("Form", "..."))
        self.neuronGifLabel.setText(_translate("Form", "TextLabel"))
        self.TabWidgetApp.setTabText(self.TabWidgetApp.indexOf(self.tab_3), _translate("Form", "Нейронная сеть"))

